Fixes everywhere

diff --git a/on-boot-script/remote_install b/on-boot-script/remote_install
--- a/on-boot-script/remote_install
+++ b/on-boot-script/remote_install
@@ -6,7 +6,7 @@ SYSTEMCTL_PATH="/etc/systemd/system/udm-boot.service"
 SYMLINK_SYSTEMCTL="/etc/systemd/system/multi-user.target.wants/udm-boot.service"
 
 CNI_PLUGINS_SCRIPT_RAW_URL="https://raw.githubusercontent.com/boostchicken/udm-utilities/HEAD/cni-plugins/05-install-cni-plugins.sh"
-CNI_PLUGINS_ON_BOOT_FILENAME="$(basename "$CNI_PLUGINS_SCRIPT")"
+CNI_PLUGINS_ON_BOOT_FILENAME="$(basename "$CNI_PLUGINS_SCRIPT_RAW_URL")"
 
 CNI_BRIDGE_SCRIPT_RAW_URL="https://raw.githubusercontent.com/gtrabanco/udm-utilities/master/on-boot-script/examples/udm-networking/on_boot.d/05-cni-bridge.sh"
 CNI_BRIDGE_ON_BOOT_FILENAME="06-cni-bridge.sh"
@@ -47,16 +47,21 @@ get_persistent_path() {
   IFS_COPY="$IFS"
   IFS="/"
 
-  if [ -d "/data" ]; then
+  if [ -d "/mnt/data" ]; then
+    DATA_DIR="/mnt/data${*:+/$*}"
+  elif [ -d "/data" ]; then
     DATA_DIR="/data${*:+/$*}"
   else
-    DATA_DIR="/mnt/data${*:+/$*}"
+    echo "ERROR: No persistent storage found." 1>&2
+    exit 1
   fi
   
   mkdir -p "$DATA_DIR"
 
+  echo "$DATA_DIR"
+
   IFS="$IFS_COPY"
-  unset IFS_COPY
+  unset IFS_COPY DATA_DIR
 }
 
 get_latest_download_url() {
@@ -99,15 +104,34 @@ install_on_boot_udm_series() {
   unset download_url tmp_path
 }
 
+# Credits @peacey: https://github.com/boostchicken/udm-utilities/issues/214#issuecomment-886869295
+udmse_on_boot_systemd() {
+cat << EOF
+[Unit]
+Description=Run On Startup UDM
+Wants=network-online.target
+After=network-online.target
+
+[Service]
+Type=forking
+ExecStart=bash -c 'mkdir -p /mnt/data/on_boot.d && find -L /mnt/data/on_boot.d -mindepth 1 -maxdepth 1 -type f -print0 | sort -z | xargs -0 -r -n 1 -- bash -c \'if test -x "$0"; then echo "%n: running $0"; "$0"; else case "$0" in *.sh) echo "%n: sourcing $0"; . "$0";; *) echo "%n: ignoring $0";; esac; fi\''
+
+[Install]
+WantedBy=multi-user.target
+
+EOF
+}
+
 install_on_boot_udr_se() {
   systemctl disable udm-boot
   systemctl daemon-reload
   rm -f "$SYMLINK_SYSTEMCTL"
 
-  echo "Doanloading systemctl file..."
-  curl -sLJo "$SYSTEMCTL_PATH" "$UDM_BOOT_RAW_URL" || return 1
+  echo "Creating systemctl service file"
+  udmse_on_boot_systemd > "$SYSTEMCTL_PATH" || return 1
   sleep 1s
 
+  echo "Enabling UDM boot..."
   systemctl daemon-reload
   systemctl enable "udm-boot"
   systemctl start "udm-boot"
@@ -122,6 +146,7 @@ ON_BOOT_D_PATH="$(get_persistent_path "on_boot.d")"
 
 case "$(udm_model)" in
   udm|udmpro)
+    echo "UDM/Pro detected, installing on-boot script..."
     depends_on podman
 
     if ! install_on_boot_udm_series; then
@@ -133,6 +158,7 @@ case "$(udm_model)" in
     echo "UDM Boot Script installed"
     ;;
   udr|udmse)
+    echo "UDR/UDMSE detected, installing on-boot script..."
     depends_on systemctl
 
     if ! install_on_boot_udr_se; then
@@ -148,15 +174,20 @@ case "$(udm_model)" in
     exit 1
     ;;
 esac
+echo
 
 
-echo "Downloading CNI plugins script..."
-if
-  ! download_on_path "${ON_BOOT_D_PATH}/${CNI_PLUGINS_ON_BOOT_FILENAME}" "$CNI_PLUGINS_SCRIPT_RAW_URL"
-then
-  echo
-  echo "Failed to download CNI plugins script" 1>&2
-  exit 1
+if [ ! -f "${ON_BOOT_D_PATH}/${CNI_PLUGINS_ON_BOOT_FILENAME}" ]; then
+  echo "Downloading CNI plugins script..."
+  if
+    ! download_on_path "${ON_BOOT_D_PATH}/${CNI_PLUGINS_ON_BOOT_FILENAME}" "$CNI_PLUGINS_SCRIPT_RAW_URL"
+  then
+    echo
+    echo "Failed to download CNI plugins script" 1>&2
+    exit 1
+  fi
+else
+  echo "Downloading of CNI bridge script skipped"
 fi
 chmod +x "${ON_BOOT_D_PATH}/${CNI_PLUGINS_ON_BOOT_FILENAME}"
 echo "CNI plugins script installed"
@@ -164,20 +195,25 @@ echo "Executing CNI plugins script..."
 "${ON_BOOT_D_PATH}/${CNI_PLUGINS_ON_BOOT_FILENAME}" || true
 echo
 
-echo "Downloading CNI bridge script..."
-if
-  ! download_on_path "${ON_BOOT_D_PATH}/${CNI_BRIDGE_ON_BOOT_FILENAME}" "$CNI_BRIDGE_SCRIPT_RAW_URL"
-then
-  echo
-  echo "Failed to download CNI bridge script" 1>&2
-  exit 1
+
+if [ ! -f "${ON_BOOT_D_PATH}/${CNI_BRIDGE_ON_BOOT_FILENAME}" ]; then
+  echo "Downloading CNI bridge script..."
+  if
+    ! download_on_path "${ON_BOOT_D_PATH}/${CNI_BRIDGE_ON_BOOT_FILENAME}" "$CNI_BRIDGE_SCRIPT_RAW_URL"
+  then
+    echo
+    echo "Failed to download CNI bridge script" 1>&2
+    exit 1
+  fi
+else
+  echo "Downloading of CNI bridge script skipped"
 fi
 chmod +x "${ON_BOOT_D_PATH}/${CNI_BRIDGE_ON_BOOT_FILENAME}"
 echo "CNI bridge script installed"
 echo "Executing CNI bridge script..."
+echo "${ON_BOOT_D_PATH}/${CNI_BRIDGE_ON_BOOT_FILENAME}"
 "${ON_BOOT_D_PATH}/${CNI_BRIDGE_ON_BOOT_FILENAME}" || true
 echo
-
 
 echo "On boot script installation finished"
 echo
